name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VERSION: '3.0.0-rc.3'
      SERVERPOD_PASSWORD_database: 'YPnYKLbdl5ZO3EMBkw-Lw19tPwngLJuc'
      SERVERPOD_PASSWORD_redis: '7VZRSZEUL-bOiz1oREqrxydXR64wLm3z'

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'

      - name: Start containers
        working-directory: t24_server
        run: docker compose up --build -d

      - name: Install dependencies
        working-directory: t24_server
        run: dart pub get

      - name: Install Serverpod CLI
        working-directory: t24_server
        run: dart pub global activate serverpod_cli $VERSION

      - name: Run Serverpod generator
        working-directory: t24_server
        run: serverpod generate

      - name: Run tests
        working-directory: t24_server
        run: dart test

      - name: Stop containers
        if: always()
        working-directory: t24_server
        run: docker compose down -v
